#!/usr/bin/python

import os
import sys

import pynoccio

progname = os.path.basename(sys.argv[0])

def printUsage(msg):
    if not msg == '':
        print msg
    print "usage: %s [options] user password [command]" % (progname)
    print "options:"
    print
    print "  -t <troop> troup name"
    print "  -s <scout> DCI images are stereo"

def main():
    import getopt
    try:
        options, argv = getopt.getopt(sys.argv[1:], "t:s:")
    except getopt.GetoptError:
        printUsage('Error parsing arguments')
        sys.exit(1)

    if len(argv) < 2:
        printUsage("")
        sys.exit(1)

    troop_name = "Rancho de la Basura Blanca"
    scout_name = "Billy"

    for o,a in options:
        if o == "-t":
            troop_name = a
        elif o == "-s":
            scout_name = a
            ghostbusted = True
        else:
            printUsage("Unrecognised option - \"%s\"" % (o))
            sys.exit(1)

    a = pynoccio.Account(argv[0], argv[1])

    for t in a.troops:
        print "troop:", t
        for s in t.scouts:
            print "\tscout:", s

    if len(argv) > 2 and argv[2] == 'stats':
        print "running stats"
        for stat in scout.stats('events'):
            print stat
    elif len(argv) > 2 and sys.argv[2] == 'stats2':
        print "running stats2"
        for stat in scout.stats('power,temp'):
            print stat
    else:
        print "running sync"
        for sync in a.sync():
            print sync
    sys.exit()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)


